name: Update Work Duration Badge

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-duration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Calculate duration
        id: duration
        run: |
          # Calculate work duration
          START_DATE="2024-08-01"  # August 1, 2024
          
          # Get current date in seconds since epoch
          CURRENT_DATE=$(date +%s)
          
          # Convert start date to seconds since epoch
          START_DATE_SECONDS=$(date -d "$START_DATE" +%s)
          
          # Calculate difference in seconds
          DIFF_SECONDS=$((CURRENT_DATE - START_DATE_SECONDS))
          
          # Convert to days
          DIFF_DAYS=$((DIFF_SECONDS / 86400))
          
          # Calculate years, months, days
          YEARS=$((DIFF_DAYS / 365))
          REMAINING_DAYS=$((DIFF_DAYS % 365))
          MONTHS=$((REMAINING_DAYS / 30))
          DAYS=$((REMAINING_DAYS % 30))
          
          # Format duration for shields.io badge
          # Format should be URL-friendly (no spaces, special chars)
          DURATION_TEXT=""
          
          if [ "$YEARS" -gt "0" ]; then
            if [ "$YEARS" -eq "1" ]; then
              DURATION_TEXT="${YEARS}_year"
            else
              DURATION_TEXT="${YEARS}_years"
            fi
          fi
          
          if [ "$MONTHS" -gt "0" ]; then
            if [ -n "$DURATION_TEXT" ]; then
              DURATION_TEXT="${DURATION_TEXT}_"
            fi
            
            if [ "$MONTHS" -eq "1" ]; then
              DURATION_TEXT="${DURATION_TEXT}${MONTHS}_month"
            else
              DURATION_TEXT="${DURATION_TEXT}${MONTHS}_months"
            fi
          fi
          
          if [ "$DAYS" -gt "0" ]; then
            if [ -n "$DURATION_TEXT" ]; then
              DURATION_TEXT="${DURATION_TEXT}_"
            fi
            
            if [ "$DAYS" -eq "1" ]; then
              DURATION_TEXT="${DURATION_TEXT}${DAYS}_day"
            else
              DURATION_TEXT="${DURATION_TEXT}${DAYS}_days"
            fi
          fi
          
          # If there's no duration yet (negative time), set a default
          if [ -z "$DURATION_TEXT" ]; then
            DURATION_TEXT="just_started"
          fi
          
          echo "Duration text: $DURATION_TEXT"
          echo "duration_text=$DURATION_TEXT" >> $GITHUB_OUTPUT
          
      - name: Update README with shields.io badge
        run: |
          DURATION_TEXT="${{ steps.duration.outputs.duration_text }}"
          BADGE_URL="https://img.shields.io/badge/duration-${DURATION_TEXT}-blue"
          
          # Create new line for README with shields.io badge
          NEW_LINE="- 🛡️ I'm currently working at Sopra Steria with cybersecurity since August 2024 ![Duration](${BADGE_URL})"
          
          # Replace the line in README.md
          sed -i "s|- 🛡️ I'm currently working at Sopra Steria with cybersecurity.*$|$NEW_LINE|g" README.md
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add README.md
          git commit -m "Update work duration badge" || echo "No changes to commit"
          git push
